language: php

php:
  - hhvm
  - nightly
  - 7
  - 5.6
  - 5.5

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - phpenv config-rm xdebug.ini

script:
  - composer test
